server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: alonso
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true
    properties: 
      hibernate:
        format_sql: true
    